# **Support Vector Machines**

# A SVM classification demonstration with different kernels

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.svm import SVC
import pandas as pd
import numpy as np

Classification on breast cancer dataset

In [ ]:
cancer = datasets.load_breast_cancer()

dataframe1 = pd.DataFrame(cancer.data)
print(dataframe1.shape)
print(dataframe1.head())

X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, test_size=0.2,random_state = 1)

(569, 30)
      0      1       2       3   ...      26      27      28       29
0  17.99  10.38  122.80  1001.0  ...  0.7119  0.2654  0.4601  0.11890
1  20.57  17.77  132.90  1326.0  ...  0.2416  0.1860  0.2750  0.08902
2  19.69  21.25  130.00  1203.0  ...  0.4504  0.2430  0.3613  0.08758
3  11.42  20.38   77.58   386.1  ...  0.6869  0.2575  0.6638  0.17300
4  20.29  14.34  135.10  1297.0  ...  0.4000  0.1625  0.2364  0.07678

[5 rows x 30 columns]


In [ ]:
########################## polynomial kernel ####################################
poly_svc_classifier = SVC(kernel='poly', degree=8)
poly_svc_classifier.fit(X_train, y_train)

poly_y_pred = poly_svc_classifier.predict(X_test)

# evaluating the algorithm
print("Confusion matrix for Polynomial kernel SVC")
print(confusion_matrix(y_test, poly_y_pred))
print(classification_report(y_test, poly_y_pred))
print("-----------------------------------------------------------")

############################  gausian kernel  ############################

gausian_svc_classifier = SVC(kernel='rbf')
gausian_svc_classifier.fit(X_train, y_train)

gausian_y_pred = gausian_svc_classifier.predict(X_test)

# evaluating the algorithm
print("Confusion matrix for gausian kernel SVC")
print(confusion_matrix(y_test, gausian_y_pred))
print(classification_report(y_test, gausian_y_pred))
print("-----------------------------------------------------------")


####################### Sigmoid Kernel   ####################################
sigmoid_svc_classifier = SVC(kernel='sigmoid')
sigmoid_svc_classifier.fit(X_train, y_train)

sigmoid_y_pred = sigmoid_svc_classifier.predict(X_test)

# evaluating the algorithm
print("Confusion matrix for sigmoid kernel SVC")
print(confusion_matrix(y_test, sigmoid_y_pred))
print(classification_report(y_test, sigmoid_y_pred))

Confusion matrix for Polynomial kernel SVC
[[26 16]
 [ 0 72]]
              precision    recall  f1-score   support

           0       1.00      0.62      0.76        42
           1       0.82      1.00      0.90        72

    accuracy                           0.86       114
   macro avg       0.91      0.81      0.83       114
weighted avg       0.89      0.86      0.85       114

-----------------------------------------------------------
Confusion matrix for gausian kernel SVC
[[31 11]
 [ 0 72]]
              precision    recall  f1-score   support

           0       1.00      0.74      0.85        42
           1       0.87      1.00      0.93        72

    accuracy                           0.90       114
   macro avg       0.93      0.87      0.89       114
weighted avg       0.92      0.90      0.90       114

-----------------------------------------------------------
Confusion matrix for sigmoid kernel SVC
[[10 32]
 [34 38]]
              precision    recall  f1-score   

Classification on iris dataset

In [ ]:
from sklearn.datasets import load_iris

#loading the dataset
iris_data = load_iris()
dataframe1 = pd.DataFrame(iris_data.data)

#arranging the dataset as features and targets
X = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
y = iris_data.target

#chekking datasets attributes
print(dataframe1.head())
print(dataframe1.shape)

# Splitting as test / train
X_train_iris, X_test_iris, y_train_iris, y_test_iris = train_test_split(iris_data.data, iris_data.target, test_size=0.2,random_state=1)

     0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2
(150, 4)


In [ ]:
########################## polynomial kernel ####################################
poly_svc_classifier2 = SVC(kernel='poly', degree=8)
poly_svc_classifier2.fit(X_train_iris, y_train_iris)

poly_y_pred2 = poly_svc_classifier2.predict(X_test_iris)

# evaluating the algorithm
print("Confusion matrix for Polynomial kernel SVC")
print(confusion_matrix(y_test_iris, poly_y_pred2))
print(classification_report(y_test_iris, poly_y_pred2))
print("-----------------------------------------------------------")

############################  gausian kernel  ############################

gausian_svc_classifier = SVC(kernel='rbf')
gausian_svc_classifier.fit(X_train_iris, y_train_iris)

gausian_y_pred = gausian_svc_classifier.predict(X_test_iris)

# evaluating the algorithm
print("Confusion matrix for gausian kernel SVC")
print(confusion_matrix(y_test_iris, gausian_y_pred))
print(classification_report(y_test_iris, gausian_y_pred))
print("-----------------------------------------------------------")


####################### Sigmoid Kernel   ####################################
sigmoid_svc_classifier = SVC(kernel='sigmoid')
sigmoid_svc_classifier.fit(X_train_iris, y_train_iris)

sigmoid_y_pred = sigmoid_svc_classifier.predict(X_test_iris)

# evaluating the algorithm
print("Confusion matrix for sigmoid kernel SVC")
print(confusion_matrix(y_test_iris, sigmoid_y_pred))
print(classification_report(y_test_iris, sigmoid_y_pred))

Confusion matrix for Polynomial kernel SVC
[[11  0  0]
 [ 0 12  1]
 [ 0  1  5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.92      0.92      0.92        13
           2       0.83      0.83      0.83         6

    accuracy                           0.93        30
   macro avg       0.92      0.92      0.92        30
weighted avg       0.93      0.93      0.93        30

-----------------------------------------------------------
Confusion matrix for gausian kernel SVC
[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.92      0.96        13
           2       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

---------------------

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Classification on wine dataset

In [ ]:
from sklearn.datasets import load_wine

#loading the dataset
wine_data = load_wine()
dataframe2 = pd.DataFrame(wine_data.data)

#arranging the dataset as features and targets
X = pd.DataFrame(wine_data.data, columns=wine_data.feature_names)
y = wine_data.target

#chekking datasets attributes
print(dataframe2.head())
print(dataframe2.shape)

# Splitting as test / train
X_train_wine, X_test_wine, y_train_wine, y_test_wine = train_test_split(wine_data.data, wine_data.target, test_size=0.2,random_state=1)

      0     1     2     3      4     5   ...    7     8     9     10    11      12
0  14.23  1.71  2.43  15.6  127.0  2.80  ...  0.28  2.29  5.64  1.04  3.92  1065.0
1  13.20  1.78  2.14  11.2  100.0  2.65  ...  0.26  1.28  4.38  1.05  3.40  1050.0
2  13.16  2.36  2.67  18.6  101.0  2.80  ...  0.30  2.81  5.68  1.03  3.17  1185.0
3  14.37  1.95  2.50  16.8  113.0  3.85  ...  0.24  2.18  7.80  0.86  3.45  1480.0
4  13.24  2.59  2.87  21.0  118.0  2.80  ...  0.39  1.82  4.32  1.04  2.93   735.0

[5 rows x 13 columns]
(178, 13)


In [ ]:
########################## polynomial kernel ####################################
poly_svc_classifier = SVC(kernel='poly', degree=8)
poly_svc_classifier.fit(X_train_wine, y_train_wine)

poly_y_pred = poly_svc_classifier.predict(X_test_wine)

# evaluating the algorithm
print("Confusion matrix for Polynomial kernel SVC")
print(confusion_matrix(y_test_wine, poly_y_pred))
print(classification_report(y_test_wine, poly_y_pred))
print("-----------------------------------------------------------")

############################  gausian kernel  ############################

gausian_svc_classifier = SVC(kernel='rbf')
gausian_svc_classifier.fit(X_train_wine, y_train_wine)

gausian_y_pred = gausian_svc_classifier.predict(X_test_wine)

# evaluating the algorithm
print("Confusion matrix for gausian kernel SVC")
print(confusion_matrix(y_test_wine, gausian_y_pred))
print(classification_report(y_test_wine, gausian_y_pred))
print("-----------------------------------------------------------")


####################### Sigmoid Kernel   ####################################
sigmoid_svc_classifier = SVC(kernel='sigmoid')
sigmoid_svc_classifier.fit(X_train_wine, y_train_wine)

sigmoid_y_pred = sigmoid_svc_classifier.predict(X_test_wine)

# evaluating the algorithm
print("Confusion matrix for sigmoid kernel SVC")
print(confusion_matrix(y_test_wine, sigmoid_y_pred))
print(classification_report(y_test_wine, sigmoid_y_pred))

Confusion matrix for Polynomial kernel SVC
[[11  2  1]
 [ 1 12  0]
 [ 0  9  0]]
              precision    recall  f1-score   support

           0       0.92      0.79      0.85        14
           1       0.52      0.92      0.67        13
           2       0.00      0.00      0.00         9

    accuracy                           0.64        36
   macro avg       0.48      0.57      0.50        36
weighted avg       0.54      0.64      0.57        36

-----------------------------------------------------------
Confusion matrix for gausian kernel SVC
[[11  0  3]
 [ 1 11  1]
 [ 0  8  1]]
              precision    recall  f1-score   support

           0       0.92      0.79      0.85        14
           1       0.58      0.85      0.69        13
           2       0.20      0.11      0.14         9

    accuracy                           0.64        36
   macro avg       0.57      0.58      0.56        36
weighted avg       0.62      0.64      0.61        36

---------------------

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
